server:
  port: 8082
  servlet:
    context-path: /ui
  session:
    cookie: UISESSION
security:
  basic: false
  oauth2:
    client:
      clientId: sso-client-1
      clientSecret: topsecret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me
spring:
  thymeleaf:
    cache: false