server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emall-user
    username: root
    password: root123
    hikari:
      maximum-pool-size: 1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
      sql: debug